import 'dotenv/config';
import express from 'express';
import cors from 'cors';
const app=express(); app.use(cors()); app.use(express.json({limit:'8mb'}));
const geminiKeys=[process.env.GEMINI_KEY_1,process.env.GEMINI_KEY_2,process.env.GEMINI_KEY_3,process.env.GEMINI_KEY_4,process.env.GEMINI_KEY_5].filter(Boolean);
let currentKeyIndex=0;
function getNextGeminiKey(){if(!geminiKeys.length)throw new Error('No Gemini API keys found.');const key=geminiKeys[currentKeyIndex];currentKeyIndex=(currentKeyIndex+1)%geminiKeys.length;return key}
function cleanUserName(v){return typeof v==='string'?v.replace(/[<>]/g,'').trim().slice(0,120):''}
async function geminiRequest(model,body){const key=getNextGeminiKey();const r=await fetch(`https://generativelanguage.googleapis.com/v1beta/models/${model}:generateContent`,{method:'POST',headers:{'Content-Type':'application/json','x-goog-api-key':key},body:JSON.stringify(body)});const d=await r.json();if(!r.ok)throw new Error(d?.error?.message||'Gemini request failed');return d}
app.post('/api/chat',async(req,res)=>{try{const prompt=typeof req.body.prompt==='string'?req.body.prompt.trim():'';const userName=cleanUserName(req.body.userName);const image=req.body.image;if(!prompt&&!image)return res.status(400).json({error:'Prompt or image is required.'});let imagePart=null;if(image){const allowed=['image/jpeg','image/png','image/webp','image/gif','image/heic','image/heif'];if(!allowed.includes(image.mimeType)||typeof image.data!=='string'||image.data.length>5000000)return res.status(400).json({error:'Invalid or oversized image.'});imagePart={inlineData:{mimeType:image.mimeType,data:image.data}}}const system=`You are Entity AI, the assistant inside the Entity AI app. The current logged-in user's name is ${JSON.stringify(userName||'not provided')}. If asked for the user's name, use it when available. The creator and owner of Entity AI is Damar Aman. If asked who created Entity AI, who your owner is, or who owns Entity AI, answer: Damar Aman. Do not claim Google owns Entity AI. Gemini is only the underlying model/service. Be helpful, accurate and concise.`;const parts=[{text:system+'\n\nUser: '+prompt}];if(imagePart)parts.push(imagePart);const d=await geminiRequest('gemini-2.5-flash',{contents:[{parts}]});const reply=d?.candidates?.[0]?.content?.parts?.filter(p=>p.text).map(p=>p.text).join('\n')||'No reply generated.';res.json({reply})}catch(e){console.error(e);res.status(500).json({error:'Failed to generate response.',details:e?.message||'Unknown error'})}});
app.post('/api/generate-image',async(req,res)=>{try{const prompt=typeof req.body.prompt==='string'?req.body.prompt.trim():'';if(!prompt)return res.status(400).json({error:'Image prompt is required.'});if(prompt.length>2000)return res.status(400).json({error:'Image prompt is too long.'});const d=await geminiRequest('gemini-3.1-flash-image',{contents:[{parts:[{text:prompt}]}],generationConfig:{responseModalities:['IMAGE'],responseFormat:{image:{aspectRatio:'1:1',imageSize:'1K'}}}});const p=d?.candidates?.[0]?.content?.parts?.find(x=>x.inlineData?.data||x.inline_data?.data);if(!p)throw new Error('No image was returned by the image model.');const i=p.inlineData||p.inline_data;res.json({image:i.data,mimeType:i.mimeType||i.mime_type||'image/png',text:'Generated image'})}catch(e){console.error('Image generation error:',e);res.status(500).json({error:'Image generation failed.',details:e?.message||'Unknown error'})}});
app.get('/api/health',(req,res)=>res.json({status:'ok',service:'Entity AI'}));const PORT=process.env.PORT||3000;app.listen(PORT,'0.0.0.0',()=>console.log(`Entity AI Server running on port ${PORT}`));
